=== Veeam Settings

Enabled:: Enable the Veeam integration
Default Backup Provider:: Sets Veeam as the Default Backup Provider in {morpheus}. Backup Providers can be configured per
Visibility:: Sets visibility in multi-tenant {morpheus} environments.
* Public: Accessible by all Tenants
* Private: Accessible only to the Tenant the Veeam integration is added.
+
Host:: Host name or the IP address of the Veeam Backup Enterprise Manager. This is the same host that you use to access the Veeam Backup Enterprise Manager browser-based user interface.
Port:: The HTTP(S) port of the Veeam Backup Enterprise Manager API. The default is 9399.
Username:: The username used to authenticate with the Veeam Backup Enterprise Manager.
Password:: The password used to authenticate with the Veeam Backup Enterprise Manager.
Backup Repositories:: Once credentials are authenticated, search will populate available Veeam Repositories to select from.
Backup Job Templates:: The backup jobs configured in the Veeam Backup and Replication Console that can be cloned when creating new backup jobs.
Refresh Available Jobs:: Use to sync newly created Jobs in Veeam.
