== 2.11.4 Release Notes

=== New Features

Trial Version Setting on Virtual Images Advanced Options- Flagging a Windows Image as Trial Version will re-arm the trial during provisioning
Import as Image added to Nutanix
Fix for Nutanix - Windows- Create Additional user
Console Copy & Paste
Nutanix: Network & Disk Type selection
Duplicate Image fixes
VMware Folders
Roles -> Feature Access -> Monitoring, Backups, Logs : User options added.
VMware: Thin/Thick cloud option
?VMware: Provision Boot ISO
?VMware: Eject Disks
User Scoping

Thick Provisioning option for VMware
Disk and Network type selection added to Nutanix
Updates for AWS Windows 2012 R2 AMI Node Type
Display Name column added to Infoblox IP Pools
F5 Load Balancer Improvements
HA Proxy Load Balancer Improvements
Citrix Load Balancer Improvements
Chef Improvements
Fix for browser language settings adding commas in `Plans & Pricing - Pricing`
Fix for Hyper-V and Openstack technology types in Library -> Node Type -> Image dropdown
Fix for NFS image upload
Fix for storage providers in archives
Process Service improvements
Fix for VMware image duplication
Fix for extra Sub-Tenant groups automatically being created during Sub-Tenant creation.
Fix for
UI/API/CLI Security Improvements

Provisioning: Allow Force Delete
