== v3.0 Release Notes

New Integrations::
* Kubernetes
* Cloud Foundry
* vCloud Director
* UpCloud
* SCVMM
* Jenkins
* GitHub

New App & Template wizard::
* Completely rebuilt Apps and Templates section with multi-config, Raw json and yaml input/output, locking fields and boot order added.
New Analytics::
* Completely rebuilt Analytics section with Utilization, Instance and Instance Type analytic reports and data visualizations. Quickly analyze storage, cpu or ram usage across clouds or teams, or compare utilization vs cost per resource.
Guidance::
* The new Guidance feature can analyze your infrastructure and recommend actions to optimize resource utilization with projected cost savings. Morpheus can then act on those recommendations by resizing, shutting down or moving the resources to ensure money isn't being wasted on underutilized assets.

Morpheus Image Building Service::
* Automate your images builds directly in Morpheus.

User Groups::
* Select a Group during provisioning to have users created for Group members on the instance.
* Credentials will be removed from the instance when a member is removed from a group.

User Settings Improvements::
* Default Group and Cloud added
* Per user Linux and Windows User Settings added to automatically create during provisioning.
* User Photos Added
* Users automatically created during provisioning.
