version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: conf.py
  fail_on_warning: false

python:
  install:
    - requirements: requirements.txt

formats:
  - pdf

search:
  ignore:
    - 'provisioning/catalog/*'
