== Dashboard *format

The Dashboard is a single pane of glass showing quick, easy to read performance and configuration information about the {morpheus} Environment.

There are four gauges across the top of the dashboard page showing quick system stats like number of instances, monitoring status, log messages, and backups.

The my Instances section shows quick information about 5 favorite instances like Type, IP and Port. Click on ALL to be taken directly to the instances page.

The monitoring section displays an overall health, availability statistics, as well as response time and any open incidents requiring action.

Recent Activity is displayed on the right side of the dashboard page. Items like instance provisioning and deletion, backups, and alerts are displayed here.

All {morpheus} logs are application aware. Log information from hypervisors, servers, and applications are pushed up into the {morpheus} controller node and made searchable and actionable. Choose a timeframe from the Logs pane to view statistics or click List to view all log information.

The backup pane at the bottom of the page shows statistics about {morpheus} backups. Information about success and failure rates and the number of backups run versus scheduled is available here. Click on the List button to be taken directly to the backups page where you can view and configure backups.
