[[pxeboot]]

== PXE Boot

Overview

To view boot:

Click the Infrastructure link in the navigation bar.
Select the Boot link in the sub navigation bar.
Mapping

Add Mapping

Click the Infrastructure link in the navigation bar.
Click the Boot link in the sub navigation bar.
Select the Mapping tab then click the Add Mapping button.
From the New Mapping Wizard input the following information
Match Pattern: Mac address separated by ':' or an ip address filter
Description(optional): Description of the new mapping.
Active: Flag to denote the mapping as active or disabled.
Operating System: List of operating systems for the mapping.
Boot Image: Lists available PXE boot images.
Answer File: Lists available answer files.
Cloud: Lists the available clouds.
Server Mode: List of server modes: unmanaged, Managed, Bare metal host, Container host, VM host, and Container & VM host.
Click the Save Changes button to save.
Edit Mapping

Click the Infrastructure link in the navigation bar.
Click the Boot link in the sub navigation bar.
Click the edit icon on the row of the mapping you wish to edit.
Modify information as needed.
Click the Save Changes button to save.
Delete Mapping

Click the Infrastructure link in the navigation bar.
Click the Boot link in the sub navigation bar.
Click the delete icon on the row of the mapping you wish to delete.
Note: You will be prompted for confirmation on this action.
Answer Files

Answer files are like lists of answers for questions that you know the setup program is going to ask but the user is not prepared to answer. They contain one or more sections, and each section contains one or more properties in the form name=value.

Add Answer Files

Click the Infrastructure link in the navigation bar.
Select the Boot link in the sub navigation bar.
Select the Answer Files tab then click the Add Answer File button.
From the New Answer File Wizard input the following information
Name: Name of the answer file.
Description(optional): Description of the new answer file.
Active: Flag to denote the mapping as active or disabled.
Script Name: Name of the new answer file.
Script Version: Version of the new answer file.
Script: The script for the new answer file.
Click the Save Changes button to save.
Edit Answer File

Click the Infrastructure link in the navigation bar.
Click the Boot link in the sub navigation bar.
Select the Answer Files tab
Click the edit icon on the row of the answer file you wish to edit.
Modify information as needed.
Click the Save Changes button to save.
Delete Answer File

Click the Infrastructure link in the navigation bar.
Click the Boot link in the sub navigation bar.
Select the Answer Files tab.
Click the delete icon on the row of the answer file you wish to delete.
Note: You will be prompted for confirmation on this action.
Images


Add Images

Click the Infrastructure link in the navigation bar.
Select the Boot link in the sub navigation bar.
Select the Images tab then click the Add Image button.
From the Upload Virtual Image Wizard input the following information
Name: Name of the answer file.
Operating System: List of available operating systems.
Menu:
Storage Provider: List of available storage providers.
Image Path: Path of the image.
Visibility: Private or Public
Account: List of accounts to allow permission to this image.
Click the Save Changes button to save.
Edit Image

Click the Infrastructure link in the navigation bar.
Click the Boot link in the sub navigation bar.
Select the Images tab
Click the actions drop down and select edit.
Modify information as needed.
Click the Save Changes button to save.
Convert Image

Click the Infrastructure link in the navigation bar.
Click the Boot link in the sub navigation bar.
Select the Images tab
Click the actions drop and select convert.
Download Image

Click the Infrastructure link in the navigation bar.
Click the Boot link in the sub navigation bar.
Select the Images tab
Click the actions drop and select download.
Remove Image

Click the Infrastructure link in the navigation bar.
Click the Boot link in the sub navigation bar.
Select the Image tab.
Click the actions drop and select remove.
Note: You will be prompted for confirmation on this action.
