=== Incidents

Incident management is very important in any IT Operations environment. The ability to notify the appropriate people of an outage that requires immediate attention is critical to reducing recovery time and even preventing potential customer facing impacts. Because of this, {morpheus} provides incident management features as well as external integrations out of the box.

Incidents can be found in the `Monitoring->Incidents` section. When a check fails, an incident is automatically raised. These can vary in severity based on the user configured check severities as well as the group hierarchy (representative of redundancy).

Incidents are also grouped. If an application is impacted and multiple checks fail for that application they automatically get grouped together in one Incident that can fluctuate or escalate in severity as time progresses. These incidents can be muted so as not to affect availability and they can also be resolved manually with an option to detail resolution information.

=== Service Now

Service now integration is provided out of the box with {morpheus}. To add a service now integration simply visit the 'Monitoring Settings' section in `Admin -> Monitoring`. This allows one to map incident severity levels to equivalent severities in ServiceNow.

To enable service now simply expand the section labelled "ServiceNow" in `Admin -> Monitoring`. Toggle the enabled flag and enter the `Host`, `User`, and `Password` information required to connect to ServiceNow. The other options below include behaviors upon new incidents being opened and old incidents closing. It also includes a table for mapping {morpheus} incident serverity levels to their ServiceNow counterparts.

There are several other useful service now integrations planned for future releases and will be discussed as those features come out.


