=== Integrations

While {morpheus} provides a fantastic means for determining uptime and availability of both services and vms sometimes more is needed. A good example of this is performance application monitoring. To solve this several external integrations are provided out of the box. Even some external integrations with regards to incedent management are provided.

==== AppDynamics

*[TODO: Fill this in]*

==== NewRelic

*[TODO: Fill this in]*

=== Service Now

Service now integration is provided out of the box with {morpheus}. To add a service now integration simply visit the 'Monitoring Settings' section in `Admin -> Monitoring`. This allows one to map incident severity levels to equivalent severities in ServiceNow.

To enable service now simply expand the section labelled "ServiceNow" in `Admin -> Monitoring`. Toggle the enabled flag and enter the `Host`, `User`, and `Password` information required to connect to ServiceNow. The other options below include behaviors upon new incidents being opened and old incidents closing. It also includes a table for mapping {morpheus} incident serverity levels to their ServiceNow counterparts.

There are several other useful service now integrations planned for future releases and will be discussed as those features come out.

