[[lb]]
== Load Balancers

=== Overview

Morpheus can provision VM or Container HaProxy Load Balancers, Amazon Elastic and Application Load Balancers, Azure Load Balancers, and integrates with several external Load Balancers, including F5, A10, Citrix, and AVI.

Once created or integrated, Load Balancers are available as an option to be added during provision time or post-provisioning.

Once a Load Balancer is added to an instance, you can manually scale or configure auto-scaling based on thresholds or schedules, and burst across clouds with cloud priority.

NOTE: HaProxy VM Load Balancer option, Load Balancer detail pages, Balance Mode, Sticky Mode and Shared VIP address option are available in Morpheus 2.11.3+.

To get started, navigate to Infrastructure -> Load Balancers.

Load_Balancers___Morpheus.png

In the Load Balancers page there are two sections:

Load Balancers:: View or edit existing Load Balancers, add new Load Balancers.
Virtual Servers:: View and link to Instances that are attached to load balancers.

=== Load Balancers

The Load Balancers tab list currently available Load Balancers, which you can select, edit or delete, and is where you can create new or integrate with external Load Balancers.

==== Add a new Load Balancer:

Select Screen_Shot_2017-06-17_at_11.03.15_PM.png, chose an option, and fill in the required information:

A10 (aXAPI v3)::
* Group
* Cloud
* Name
* Description
* API Host
* API Port
* Username
* Password
* Internal IP
* Public IP
* VIP Address
* VIP Port

Amazon ALB::
* Cloud
* Name
* Description
* Scheme
* Internal
* Internet-Facing
* Amazon Subnets (Select + to add additional)
** Specify the subnets to enable for your load balancer. You can specify only one subnet per Availability Zone. You must specify subnets from at least two Availability Zones to increase the availability of your load balancer.
* Amazon Security Groups (Select + to add additional)

AVI::
* Group
* Cloud
* Name
* Description
* API Host
* API Port
* Username
* Password
* Internal IP
* Public IP
* VIP Address
* VIP Port

Azure Load Balancer::
* Cloud
* Name
* Description
* Resource Group
* Populated from cloud selection

Citrix NetScaler::
* Group
* Cloud
* Name
* Description
* API Host
* API Port
* Username
* Password

F5 BigIP (v11.4+)::
* Group
* Cloud
* Name
* Description
* API Host
* API Port
* Username
* Password
* Managment URL

F5 LineRate::
* Group
* Cloud
* Name
* Description
* API Host
* API Port
* Username
* Password
* Internal IP
* Public IP
* VIP Address
* VIP Port

HaProxy Container:: (Internal, will create a HaProxy container, must have available docker host to provision to)
* Group
* Cloud
* Name
* Description
* Plan- Select the size of HaProxy container to be provisioned

//HAProxy VM (Internal, will provision a HaProxy VM into selected cloud)
//Group
//Cloud
//Name
//Description
//Plan- Select size of HaProxy VM to be provisioned

Upon saving your new Load Balancer will be added to the Load Balancers list and available in the Load Balancer dropdown in the Provisioning Wizard Automation Section for Instance Types that have scaling enabled.

=== Load Balancer Detail Pages

In the main Load Balancer page, select an existing load balancer to go to that Load Balancers detail Page.
