[[accounts]]

== Accounts

=== Overview

The Accounts page displays a list of all accounts. This page enables users to: Create, Edit, and Delete accounts. The list of accounts displays the account Name, Role, Total Instances, Total Users, and the Created Date. Click the Account Name to drill into the Account View where you can again Edit, Delete, as well as Create Users, Edit Users, and Delete Users users belonging to the account.

=== Create Account

To create account

Select the Admin link in the navigation bar.

Select the Accounts link in the sub navigation bar.

Click the Create Account button.

From the New Account wizard input

Name
Description(optional)
Base Role Primary role of the account. All roles created within the account must inherit this role as the base role.
Limits restricts the amount of Storage and Memory allocated to the account.
Click the Save Changes button.

=== Edit Account

To edit account

Select the Admin link in the navigation bar.

Select the Accounts link in the sub navigation bar.

Click the Edit pencil icon on the row of the account to edit.

Edit the following from the Edit Account Wizard:

Name
Description(optional)
Base Role Primary role of the account. All roles created within the account must inherit this role as the base role.
Limits restricts the amount of Storage and Memory the account is allocated.
Click the Save Changes button.

=== Delete Account

To delete account

Select the Admin link in the navigation bar.
Select the Accounts link in the sub navigation bar.
Click the Delete trashcan icon on the row of the account to delete.
Note: You will be prompted for confirmation on this action.
=== Account View

Account View displays a list of users belonging to the account and their Name, Username, Email, and Role. From this page: Create, Edit, and Delete users.

To View Account:

Select the Admin link in the navigation bar.
Select the Accounts link in the sub navigation bar.
Click the Account Name on the row of the account to view.
=== Create User

To create user

Select the Admin link in the navigation bar.

Select the Accounts link in the sub navigation bar.

Click the Account Name on the row of the account where the user will be added.

Click the Create User button.

From the New User wizard input the fields below

First Name of the user being created
Last Name of the user being created
Username used to login
Email address of the new user
Role to be inherited by the user
Password
Limits restricts the amount of Storage and Memory the user can provision.
Click Save Changes.

=== Edit User

To edit user

Select the Admin link in the navigation bar.

Select the Accounts link in the sub navigation bar.

Click the Account Name on the row of the account containing the user to be edited.

Click the Edit pencil icon of the row of the to edit.

Edit the following from the Edit User Wizard:

First Name of the user
Last Name of the user
Username used to login
Email address of the user
Role to be inherited by the user
Password
Limits restricts the amount of Storage and Memory the user can provision.
Click Save Changes.

=== Delete User

To delete user

Select the Admin link in the navigation bar.
Select the Accounts link in the sub navigation bar.
Click the Account Name on the row of the account containing the user.
Click the Delete trashcan icon of the row of the user to delete.
NOTE: You will be prompted for confirmation on this action.
