=== Instances

Instances is a great starting point for taking advantage of self service features and spinning up both vms and containers. In {morpheus} it may be advisable to cover the definition of a few terms used within the application so as to reduce confusion.

* *Instance* - A set of containers or virtual machines that can correlate to a single horizontally scalable entity or a service suite like a database. (It is important to note that an instance can contain one or more containers/vms depending on the instance type and configuration).
* *Container* - Typically a docker container provisioned via a {morpheus} Docker host.
* *Virtual Machine* - A virtualized compute server provisioned onto various hypervisor hosts.

==== Getting Started

The instance catalog is the one stop shop for selecting items to be provisioned and pieced together. It contains not only basic container and vm options but also tailored services for SQL databases, NoSQL databases, cache stores, message busses, web servers, and even full fledged apps. The list contains a lot of items to choose from and they are represented to the user based on what provisioning engines are enabled and integrated in the {morpheus} environment.

To get started, simply click the `+ Add Instance` button in the upper right of the `Provisioning -> Instances` section. A modal will display allowing the catalog to be searched. Once an item is selected it is just a matter of following the steps through the wizard.

TIP: The instance catalog can be customized via role based access control thereby restricting access to non sanctioned catalog items, as well as added to via the `Provisioning -> Library` section. It is completely customizable.

The next step will ask for a Group and Cloud to be selected. The Group is an abstract representation that can contain multiple cloud integrations. These cloud integrations can also be in multiple groups and is also useful for using role based access control to restrict provisioning access and set retainment policies. If the environment is new and these do not yet exist, It may be advisable to refer to the main section on Getting started by setting up some cloud integrations and infrastructure first. The wizard continues by allowing us to choose a name for the instance as well as an environment.

NOTE: Currently the Environment option is mostly useful for presenting the user with informative metadata around the instance when coming back to it later.

Moving on, it is now time to configure the Instance. Depending on the option that was chosen and the Instance Configuration that is chosen fields will change. This can include cloud specific fields (i.e. Datastore for Vmware or Network). There will also be options like initial username. Some of these fields are optional and will be represented as such.

Configuration options provided in this screen are very powerful. An example is Mysql where a Master/Slave or Master/Master layout can be selected. These configurations will automatically deploy two MySQL vms or containers and link them together to provide replication. These types of configurations exist for a wide range of instance types and are optimized for high performance and scale. It is even possible to provision entire sharded Mongo clusters.

One last step before the instance can be provisioned is the `Automation` step. This wizard step may or may not appear depending on the capabilities of the instance type or previous configurations in the account. It is here one can easily select a post provisioning workflow to run ( see more on Tasks and Workflows), assign a load balancer, or even configure the backup job that gets created.

Now that the steps are completed for provisioning the selected instance type , simply review your selections and complete. The instance will automatically show up in the instances list and its provisioning state will be represented. Depending on what was provisioned this step can range from seconds to minutes (typically a container configuration will be rather quick if the instance type has previously been provisioned before.)

==== Instance Details

Once the instance is completed, the status will change to "Running". Clicking on an instance will present the viewer with loads of useful information, including stats like CPU, Memory, Storage, IOPS, and even Network throughput. There are several sections within an Instance page that provide useful capabilities to the user.

* Summary - Stats and status information
* Deploy - Track deployment history for instance types that support deployments or manually kick off a deployment (only visible for instance types that support deployments)
* Settings - Some instance types support custom configuration settings (i.e. mysql presents the my.ini)
* Network - Useful for configuring security groups and access to the instance.
* Monitoring - Quick summary of the monitoring system and all checks that were configured to test teh state of the instance
* Backups - Quick backup dashboard. Useful for viewing historical backups as well as kicking off new ones.
* Logs - View all aggregated logs from the containers or vms representing the instance.
* Environment - View the environment variables presented to the instances or exported by the instances via Apps (more on this in the Apps section). Even see Imported environment variables that may be referenced by the running instance.
* Scale - For instances that support load balancing and auto scaling. Easily configure auto scaling thresholds and load balancer settings that pertain to a particular instance.
* Console - Access the instance or container via a clientless Console supporting SSH, RDP, VNC, and even hypervisor level remote consoles.


[TODO Subsection for each tab listed above]

