2.11.2 and prior

== Overview

The Reports page contains 3 different views: Server Capacity,App Capacity, and Recent Activity. Each of these views includes an option to filter, Print and Export.

Server Capacity:: Displays a list of servers, their cloud, ip address, number of containers, used and total storage and memory.
App Capacity:: Displays a list of apps, instance names, type, groups, max storage and memory. The list also displays containers, location, type, memory and storage.
Recent Activity:: Displays your recent activity.

== To View Reports:

=== Server Capacity

The Server Capacity tab-panel displays a list of your Servers, Cloud, IP Address, Containers, used and total Storage andMemory.

To View Server Capacity report:

. Select the Reports link in the navigation bar.
. Click the tab Server Capacity.

=== App Capacity

The App Capacity panel displays a list of your apps, their Instance Name, Type, Group, max Storage and Memory. The list also displays your Containers, Location, Type, Memory and Storage.

To View App Capacity report:

. Select the Reports link in the navigation bar.
. Click the tab App Capacity.

=== Recent Activity

The Recent Activity panel displays your recent activity. We define an activity as any major action performed on an instance or server, such as, but not limited to adding a server, deleting a server, provisioning an instance, deleting an instance, creating a backup, etc… This view can be searched and filtered by type, user, and date range.

There are 5 types of activities that are displayed: Provisioning, Monitoring, Alert, Backups, and Logs.

To review the item of the activity that occurred click the name of the activity and it will goto a new page and display that item.

NOTE: Deleted activities are displayed as an alert and do not contain a link to the event item. If the activity is not a deletion event we provide a link on the activity name to goto the item the activity occurred on.

To View Recent Activity report:

. Select the Reports link in the navigation bar.
. Click the tab Recent Activity.

Recent activity is displayed in order from recent to oldest. This view can be searched and filtered by type, user, and date range.

To filter:

. Click the filter drop down of type of filter you want to apply.
. Select the appropriate filter.
