[[virtual_images]]
UPDATE

== Virtual Images

=== Overview

The virtual image page displays a list of all images configured and available to deploy. The list of images displayed on this page displays the type, name, platform, region, and status. Drill into any image to perform actions and review detailed information.

To View Virtual Images:

Select the Provisioning link in the main navigation bar.
Select the Virtual Images link in the sub-navigation bar.

=== Add Virtual Image

To Add Virtual Image:

Select the Provisioning link in the main navigation bar.

Select the Virtual Images link in the sub-navigation bar.

Click the Add Virtual Image button.

Select the Cloud Type from the dropdown.

From the Upload Virtual Image Wizard input the following basic information:

Name of the Virtual Image.

Operating System type of the Virtual Image.

CentOS
Redhat
Ubuntu
Windows
etc.
Username

Password

Storage Provider location where the Virtual Image will be stored.
Note: You must preconfigure a Storage Provider location.

Image File(s) the location of the Virtual Image file you will be uploading.

Set Permissions

Visibility
Account
Click the Save Changes button to save.
