[[azure]]
== Azure

Azure is Microsoft's public cloud offering. Offering a full range of services and features across the globe in various datacenters. It is the equivalent of AWS for Microsoft running primarily on the Hyper-V based hypervisor. While it is a great public cloud offering, it can be somewhat difficult to get integrated with which is what this guide aims to cover.


*Features:*

* Virtual Machine Provisioning
* Backups / Snapshots
* Resource Groups
* Networks
* Marketplace Search and Provisioning
* Remote Console
* Periodic Synchronization (Limited and API-Heavy Options)
* Lifecycle Management and Resize
* Virtual Image Upload



Combine this with on premise solutions like Azure-Stack and {morpheus} can provide a single pane of glass and self service portal for managing instances scattered across both public Azure and private Azure Stack offerings.

NOTE: {morpheus} even supports integrating with CSP based accounts in Azure (typically used by managed service providers).

include::clouds/azure/getting_started.adoc[]
include::clouds/azure/docker.adoc[]
include::clouds/azure/multitenancy.adoc[]
