[[chef]]
== Chef Integration *update/format

Morpheus can integrate with one or multiple chef servers to be used as tasks and workflows in the Automation section. These workflows can then be ran during provisioning in the provisioning wizard Automation pane, or on an exiting instance by selecting Actions- Run Workflow.  Workflows can also be added to instances in the template and app sections.

=== To integrate Chef Servers in Morpheus:

. Navigate to Admin- Integrations and select "+ New Integration"

. Select Integration Type "Chef"

. Populate the following fields:

Name:: Name of the Chef Integration in Morpheus
Chef Endpoint:: url of chef server api endpoint in https://api.example.com format. Do not add /organization/xxxx here, which is populated in the Chef Organization field
Chef Version:: 12.3.0 by default, can be changed to use a different/more recent version of chef
Chef Organization::
Chef User::
User Private Key:: The private key of the user with access to this chef server
Organization Validator:: Validator key for the organization

. Click SAVE CHANGES



The added Chef Server will now appear in the Chef Server dropdown when creating a Chef Bootstrap type task.
