
=== Services *update/format

The Services section allows you to add and manage IPAM, DNS, and Service Registry integrations. These services can also be adde in the Admin - Integrations section. The following integrations are currently supported:


//add includes for services adocs

IPAM

Infoblox
Bluecat (2.11)
DNS

Microsoft DNS
Power DNS
Route 53
Service Registry

Consul
To configure any of the services, select ADD SERVICE, and fill out the required fields.

Network_Services___{morpheus}_.png

Infoblox

Name
URL (wapi url + version)
example https://x.x.x.x/wapi/v2.2.1
Username
Password

Bluecat

Name
URL
Username
Password

Microsoft DNS

Name
DNS Server
Username
Password
Zone

PowerDNS

Name
API Host
Token

Route 53

Region
Access Key
Secret Key

After Saving, your network Service integrations will be available for use. These integrations must be added to the appropriate section in {morpheus}:

IPAM integrations will populate pools in the IP Pool section, which are available for assignment to networks in the NETWORK POOL dropdown when configuring a network.
DNS integrations will populate domains in the Networks Domains section, and are available in the DOMAIN dropdown located under the Advanced Options section in Cloud, Group, and Network configurations, as well as in the Configure section of the Create Instance wizard.  DNS integrations are also available in the DNS SERVICE dropdown located under the Advanced Options section in Cloud and Group configurations.
Service Registry integrations are available in the SERVICE REGISTRY dropdown located under the Advanced Options section in Cloud and Group configurations.
