
== Morpheus v3.0

New Integrations

* Kubernetes
* Cloud Foundry
//* vCloud Director
* UpCloud
* Bluemix
* SCVMM
* Jenkins
* GitHub

Features:

New: Operations -> Guidance
Rebuilt: Operations -> Analytics
Inventory Reports Added to Operations -> Reports
Rebuilt: App & Template sections
New: Services -> Image Builder
Expanded User Settings & User Groups

New App & Template wizard::
* Completely rebuilt Apps and Templates section with multi-config, Raw json and yaml input/output, locking fields and boot order added.
New Analytics::
* Completely rebuilt Analytics section with Utilization, Instance and Instance Type analytic reports and data visualizations. Quickly analyze storage, cpu or ram usage across clouds or teams, or compare utilization vs cost per resource.
Guidance::
* The new Guidance feature can analyze your infrastructure and recommend actions to optimize resource utilization with projected cost savings. Morpheus can then act on those recommendations by resizing, shutting down or moving the resources to ensure money isn't being wasted on underutilized assets.

Morpheus Image Building Service::
* Automate your images builds directly in Morpheus.
